### PR TITLE
added support for more setup instructions on index.md and added spreadsheetSetup

### PR DESCRIPTION
**Pull request by tracykteal**

### CODE REVIEW

**Comment by fmichonneau** [comment]
This reminds me of something that came up during the Miami workshop that I think we could improve on.

I'm using LibreOffice on my laptop and it's what I used to teach the lesson. About 2/3 of the participants had Excel on Mac, and the other third Excel on Windows. It created some confusion because what I had on the screen was different from everybody else in the room.

I'm wondering if for the spreadsheet lesson we should insist that everyone installs LibreOffice and we also use LibreOffice for teaching so everyone can follow along for the challenges. I think it's close enough to Excel that participants will be able to figure out how to transpose the skills on their own, and it will make teaching smoother.

Any thoughts?

**Comment by ethanwhite** [comment]
> I'm wondering if for the spreadsheet lesson we should insist that everyone installs LibreOffice and we also use LibreOffice for teaching so everyone can follow along for the challenges

I think this is a bad idea. Asking basically all of our students to change their spreadsheet program (which is the one almost everyone uses) will be getting off on a bad foot by making it seem like we're teaching them arcane tools. A big part of the goal of this section is to start them off using using tools they are already comfortable with and that is best accomplished using Excel. So, I actually think the solution is the other way around: instructors should be required to use Excel. For folks like you and I this might mean borrowing Mac or Windows laptop, but I think it will make for a much better experience for the students.

**Comment by tracykteal** [comment]
I do think students should use Excel if they have it. They should use the tools they're already working with. There are such big differences between Windows and Mac versions of Excel though, that I'm not sure it matters as much what the instructor is teaching in. I taught in LibreOffice so that I wasn't 'native' to either group and had to make sure I was explaining things to each group and didn't run into any major problems or complaints. 

Ideally our lesson should have clear explanations for doing the hands on components for both Mac and Windows in Excel as well as LibreOffice, and give the instructors the opportunity to be versed in each. This is a lesson where I don't think we can avoid OS differences unfortunately. 

I think though the setup should read "for this lesson, if you don't have a spreadsheet program already, you can use LibreOffice" rather than "If you don't have a spreadsheet program already, for this lesson we will use LibreOffice", so I'll make that change.

**Comment by ethanwhite** [comment]
> big differences between Windows and Mac versions of Excel 

You learn something new every day. I'm totally shocked that they have meaningfully differing interfaces.

That said, I'd still lean towards teaching in Excel if possible to avoid setting the instructor off too much from what folks are using in their day to day work. I feel like differences between Mac and Windows versions of Excel are easier to swallow than "I use a spreadsheet you've never heard of".

**Comment by hlapp** [comment]
I think we're ready to merge this, right?

**Comment by tracykteal** [comment]
on the differences between Windows and Mac, the main issue is that the Windows Excel interface can look like this

clip_image001_thumb_1

with the tabs instead of menus, so you don't find things in the same place, and the instructor's excel can be pretty different than the student's. I don't actually know which version looks like which, but we run in to this, and general file navigation issues (especially with Windows 8) every time. 

In Excel with our current lessons, it's been fine so far though, as the general strategy is the same in each, and people are usually familiar enough with their own version.

**Pull request merged**
